services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - database
    env_file:
      - ./backend/secrets.env

  database:
    container_name: cern_database
    image: postgres:16
    ports:
      - "5432:5432"
    restart: always
    env_file:
      - ./backend/databases/postgres/database.production.env
    environment:
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - ../resources/database/data:/var/lib/postgresql/data
      - ../resources/database/cern_db.sql:/docker-entrypoint-initdb.d/cern_db.sql

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - database

volumes:
  database:
    driver: local
