"""add width and height fields to Image

Revision ID: 1c85099b2585
Revises: 58123c737f2e
Create Date: 2024-03-27 13:23:26.610367

"""
import sqlmodel
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c85099b2585'
down_revision: Union[str, None] = '58123c737f2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('width', sa.Integer(), nullable=False))
    op.add_column('image', sa.Column('height', sa.Integer(), nullable=False))
    op.drop_column('image', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('image', 'height')
    op.drop_column('image', 'width')
    # ### end Alembic commands ###
